name: CI

on: [push, pull_request]

jobs:
 build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.1.3
  
      - name: Set Date Variable
        id: date
        shell: pwsh
        run: |
          $today = Get-Date -Format "ddMMyyHHmmss"
          echo "Today's date is: $today"
          echo today=$today >> $env:GITHUB_OUTPUT
      
      - name: Print Today Variable
        run: |
          echo "The value of 'today' is: ${{ steps.date.outputs.today }}"
