name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.3
  
      - name: Set Date Variable
        id: date
        run: |
         $today = Get-Date -Format "ddMMyyHHmmss"
         echo "Today's date is: $today"
         echo "today=$today" >> $GITHUB_OUTPUT
        shell: pwsh
      
      - name: Print Today Variable
        run: |
          echo "The value of 'today' is: ${{ steps.date.outputs.today }}"
        shell: pwsh
