name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup MS Build
        uses: microsoft/setup-msbuild@v1.0.2
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
     
      - name: Restore NuGet Packages
        run: nuget restore BarbarianCall.sln
      
      - name: Build Release Library
        run:  msbuild BarbarianCall.sln /p:Configuration=Debug
                
      - name: Upload Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: BarbarianCall 
          path: ..\Resources\
          retention-days: 2
