name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.1.3
  
      - name: Set Date Variable
        id: date
        run: |
         $today = Get-Date -Format "ddMMyyHHmmss"
         echo "today=$today" >> $GITHUB_OUTPUT
         echo "Today's date is: $today"
