name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4.1.3

      - name: Setup MS Build
        uses: microsoft/setup-msbuild@v2
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2.0.0
     
      - name: Restore NuGet Packages
        run: nuget restore ProjectTrotter.sln
      
      - name: Build Release Library
        run:  msbuild ProjectTrotter.sln /p:Configuration=Debug
        
      - name: Setting Date Variable
        id: date
        run: echo "::set-output name=today::$(date +'%d%m%y-%H%M%S')"
                
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.2
        with:
          name: ProjectTrotter_${{ steps.date.outputs.today }}
          path: Resources\
          retention-days: 2
